from __future__ import annotations


LANGUAGE_CATALOG = {
    "python": {
        "label": "Python",
        "icon": "python.svg",
        "extension": "py",
        "extensions": ["py", "pyw"],
        "lexer": "python",
        "codemirror_mode": "python",
    },
    "javascript": {
        "label": "JavaScript",
        "icon": "javascript.svg",
        "extension": "js",
        "extensions": ["js", "mjs", "cjs"],
        "lexer": "javascript",
        "codemirror_mode": "javascript",
    },
    "typescript": {
        "label": "TypeScript",
        "icon": "typescript.svg",
        "extension": "ts",
        "extensions": ["ts"],
        "lexer": "typescript",
        "codemirror_mode": "text/typescript",
    },
    "tsx": {
        "label": "TSX",
        "icon": "react.svg",
        "extension": "tsx",
        "extensions": ["tsx"],
        "lexer": "tsx",
        "codemirror_mode": "text/typescript",
    },
    "jsx": {
        "label": "JSX",
        "icon": "react.svg",
        "extension": "jsx",
        "extensions": ["jsx"],
        "lexer": "jsx",
        "codemirror_mode": "text/jsx",
    },
    "rust": {
        "label": "Rust",
        "icon": "rust.svg",
        "extension": "rs",
        "extensions": ["rs"],
        "lexer": "rust",
        "codemirror_mode": "rust",
    },
    "go": {
        "label": "Go",
        "icon": "go.svg",
        "extension": "go",
        "extensions": ["go"],
        "lexer": "go",
        "codemirror_mode": "go",
    },
    "java": {
        "label": "Java",
        "icon": "java.svg",
        "extension": "java",
        "extensions": ["java"],
        "lexer": "java",
        "codemirror_mode": "text/x-java",
    },
    "csharp": {
        "label": "C#",
        "icon": "csharp.svg",
        "extension": "cs",
        "extensions": ["cs", "csx"],
        "lexer": "csharp",
        "codemirror_mode": "text/x-csharp",
    },
    "cpp": {
        "label": "C++",
        "icon": "cplusplus.svg",
        "extension": "cpp",
        "extensions": ["cpp", "cc", "cxx", "hpp", "hxx"],
        "lexer": "cpp",
        "codemirror_mode": "text/x-c++src",
    },
    "c": {
        "label": "C",
        "icon": "c.svg",
        "extension": "c",
        "extensions": ["c", "h"],
        "lexer": "c",
        "codemirror_mode": "text/x-csrc",
    },
    "php": {
        "label": "PHP",
        "icon": "php.svg",
        "extension": "php",
        "extensions": ["php", "phtml"],
        "lexer": "php",
        "codemirror_mode": "application/x-httpd-php",
    },
    "ruby": {
        "label": "Ruby",
        "icon": "ruby.svg",
        "extension": "rb",
        "extensions": ["rb", "rake"],
        "lexer": "ruby",
        "codemirror_mode": "ruby",
    },
    "swift": {
        "label": "Swift",
        "icon": "swift.svg",
        "extension": "swift",
        "extensions": ["swift"],
        "lexer": "swift",
        "codemirror_mode": "swift",
    },
    "kotlin": {
        "label": "Kotlin",
        "icon": "kotlin.svg",
        "extension": "kt",
        "extensions": ["kt", "kts"],
        "lexer": "kotlin",
        "codemirror_mode": "text/x-kotlin",
    },
    "html": {
        "label": "HTML",
        "icon": "html.svg",
        "extension": "html",
        "extensions": ["html", "htm"],
        "lexer": "html",
        "codemirror_mode": "htmlmixed",
    },
    "css": {
        "label": "CSS",
        "icon": "css.svg",
        "extension": "css",
        "extensions": ["css"],
        "lexer": "css",
        "codemirror_mode": "css",
    },
    "scss": {
        "label": "SCSS",
        "icon": "scss.svg",
        "extension": "scss",
        "extensions": ["scss", "sass"],
        "lexer": "scss",
        "codemirror_mode": "text/x-scss",
    },
    "sql": {
        "label": "SQL",
        "icon": "postgresql.svg",
        "extension": "sql",
        "extensions": ["sql"],
        "lexer": "sql",
        "codemirror_mode": "text/x-sql",
    },
    "bash": {
        "label": "Bash",
        "icon": "bash.svg",
        "extension": "sh",
        "extensions": ["sh", "bash", "zsh"],
        "lexer": "bash",
        "codemirror_mode": "shell",
    },
    "powershell": {
        "label": "PowerShell",
        "icon": "powershell.svg",
        "extension": "ps1",
        "extensions": ["ps1", "psm1", "psd1"],
        "lexer": "powershell",
        "codemirror_mode": "powershell",
    },
    "json": {
        "label": "JSON",
        "icon": "json.svg",
        "extension": "json",
        "extensions": ["json"],
        "lexer": "json",
        "codemirror_mode": "application/json",
    },
    "yaml": {
        "label": "YAML",
        "icon": "yaml.svg",
        "extension": "yaml",
        "extensions": ["yaml", "yml"],
        "lexer": "yaml",
        "codemirror_mode": "yaml",
    },
    "markdown": {
        "label": "Markdown",
        "icon": "markdown.svg",
        "extension": "md",
        "extensions": ["md", "markdown", "mdx"],
        "lexer": "markdown",
        "codemirror_mode": "markdown",
    },
    "xml": {
        "label": "XML",
        "icon": "xml.svg",
        "extension": "xml",
        "extensions": ["xml", "xhtml", "svg"],
        "lexer": "xml",
        "codemirror_mode": "xml",
    },
    "dart": {
        "label": "Dart",
        "icon": "dart.svg",
        "extension": "dart",
        "extensions": ["dart"],
        "lexer": "dart",
        "codemirror_mode": "dart",
    },
    "r": {
        "label": "R",
        "icon": "r.svg",
        "extension": "r",
        "extensions": ["r"],
        "lexer": "r",
        "codemirror_mode": "r",
    },
    "matlab": {
        "label": "MATLAB",
        "icon": "matlab.svg",
        "extension": "m",
        "extensions": ["m"],
        "lexer": "matlab",
        "codemirror_mode": "octave",
    },
    "scala": {
        "label": "Scala",
        "icon": "scala.svg",
        "extension": "scala",
        "extensions": ["scala", "sc"],
        "lexer": "scala",
        "codemirror_mode": "text/x-scala",
    },
    "perl": {
        "label": "Perl",
        "icon": "perl.svg",
        "extension": "pl",
        "extensions": ["pl", "pm"],
        "lexer": "perl",
        "codemirror_mode": "perl",
    },
    "lua": {
        "label": "Lua",
        "icon": "lua.svg",
        "extension": "lua",
        "extensions": ["lua"],
        "lexer": "lua",
        "codemirror_mode": "lua",
    },
    "elixir": {
        "label": "Elixir",
        "icon": "elixir.svg",
        "extension": "ex",
        "extensions": ["ex", "exs"],
        "lexer": "elixir",
        "codemirror_mode": "text/plain",
    },
    "erlang": {
        "label": "Erlang",
        "icon": "erlang.svg",
        "extension": "erl",
        "extensions": ["erl", "hrl"],
        "lexer": "erlang",
        "codemirror_mode": "erlang",
    },
    "clojure": {
        "label": "Clojure",
        "icon": "clojure.svg",
        "extension": "clj",
        "extensions": ["clj", "cljs", "cljc", "edn"],
        "lexer": "clojure",
        "codemirror_mode": "clojure",
    },
    "groovy": {
        "label": "Groovy",
        "icon": "groovy.svg",
        "extension": "groovy",
        "extensions": ["groovy", "gradle"],
        "lexer": "groovy",
        "codemirror_mode": "groovy",
    },
    "objectivec": {
        "label": "Objective-C",
        "icon": "objectivec.svg",
        "extension": "mm",
        "extensions": ["mm"],
        "lexer": "objective-c",
        "codemirror_mode": "text/x-objectivec",
    },
    "vbnet": {
        "label": "VB.NET",
        "icon": "vbnet.svg",
        "extension": "vb",
        "extensions": ["vb"],
        "lexer": "vb.net",
        "codemirror_mode": "vb",
    },
    "fsharp": {
        "label": "F#",
        "icon": "fsharp.svg",
        "extension": "fs",
        "extensions": ["fs", "fsx", "fsi"],
        "lexer": "fsharp",
        "codemirror_mode": "mllike",
    },
    "haskell": {
        "label": "Haskell",
        "icon": "haskell.svg",
        "extension": "hs",
        "extensions": ["hs", "lhs"],
        "lexer": "haskell",
        "codemirror_mode": "haskell",
    },
    "julia": {
        "label": "Julia",
        "icon": "julia.svg",
        "extension": "jl",
        "extensions": ["jl"],
        "lexer": "julia",
        "codemirror_mode": "julia",
    },
    "zig": {
        "label": "Zig",
        "icon": "zig.svg",
        "extension": "zig",
        "extensions": ["zig"],
        "lexer": "zig",
        "codemirror_mode": "text/plain",
    },
    "nim": {
        "label": "Nim",
        "icon": "nim.svg",
        "extension": "nim",
        "extensions": ["nim"],
        "lexer": "nim",
        "codemirror_mode": "text/plain",
    },
    "crystal": {
        "label": "Crystal",
        "icon": "crystal.svg",
        "extension": "cr",
        "extensions": ["cr"],
        "lexer": "crystal",
        "codemirror_mode": "text/plain",
    },
    "solidity": {
        "label": "Solidity",
        "icon": "solidity.svg",
        "extension": "sol",
        "extensions": ["sol"],
        "lexer": "solidity",
        "codemirror_mode": "text/plain",
    },
    "graphql": {
        "label": "GraphQL",
        "icon": "graphql.svg",
        "extension": "graphql",
        "extensions": ["graphql", "gql"],
        "lexer": "graphql",
        "codemirror_mode": "text/plain",
    },
    "dockerfile": {
        "label": "Dockerfile",
        "icon": "dockerfile.svg",
        "extension": "dockerfile",
        "extensions": ["dockerfile"],
        "filenames": ["dockerfile"],
        "lexer": "docker",
        "codemirror_mode": "dockerfile",
    },
    "makefile": {
        "label": "Makefile",
        "icon": "makefile.svg",
        "extension": "mk",
        "extensions": ["mk", "mak"],
        "filenames": ["makefile"],
        "lexer": "make",
        "codemirror_mode": "cmake",
    },
    "terraform": {
        "label": "Terraform",
        "icon": "terraform.svg",
        "extension": "tf",
        "extensions": ["tf", "tfvars", "hcl"],
        "lexer": "terraform",
        "codemirror_mode": "text/plain",
    },
    "vue": {
        "label": "Vue",
        "icon": "vue.svg",
        "extension": "vue",
        "extensions": ["vue"],
        "lexer": "vue",
        "codemirror_mode": "htmlmixed",
    },
    "svelte": {
        "label": "Svelte",
        "icon": "svelte.svg",
        "extension": "svelte",
        "extensions": ["svelte"],
        "lexer": "svelte",
        "codemirror_mode": "htmlmixed",
    },
}

LANGUAGES = list(LANGUAGE_CATALOG)
LANGUAGE_LABELS = {
    language: config["label"] for language, config in LANGUAGE_CATALOG.items()
}
LANGUAGE_ICONS = {
    language: config["icon"] for language, config in LANGUAGE_CATALOG.items()
}
LANGUAGE_EXTENSIONS = {
    language: config["extension"] for language, config in LANGUAGE_CATALOG.items()
}
LANGUAGE_LEXERS = {
    language: config.get("lexer", language) for language, config in LANGUAGE_CATALOG.items()
}

ICON_BY_LANGUAGE = LANGUAGE_ICONS.copy()
ICON_BY_EXTENSION: dict[str, str] = {}
ICON_BY_FILENAME: dict[str, str] = {}

for language, config in LANGUAGE_CATALOG.items():
    icon = config["icon"]
    for extension in config.get("extensions", []):
        ICON_BY_EXTENSION.setdefault(f".{extension.lower().lstrip('.')}", icon)
    for filename in config.get("filenames", []):
        ICON_BY_FILENAME.setdefault(filename.lower(), icon)

ICON_BY_EXTENSION[".rs"] = "rust-white.svg"
